// Generated by the Maven Archetype Plug-in
package com.example.components;

import java.util.ArrayList;
import java.util.List;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import er.extensions.components.ERXComponent;

public class Main extends ERXComponent {
	private static final long serialVersionUID = 1L;

	public String nameInput;
	public List<String> names = new ArrayList<>();
	public String currentName;

	public Main(WOContext context) {
		super(context);
	}

	public WOActionResults addName() {
		if (nameInput != null && !nameInput.trim().isEmpty()) {
			names.add(nameInput.trim());
			nameInput = "";
		}
		return null;
	}

	public WOActionResults viewName() {
		NameDetail nameDetailPage = pageWithName(NameDetail.class);
		nameDetailPage.selectedName = currentName;
		return nameDetailPage;
	}
}
