// Generated by the Maven Archetype Plug-in
package com.example.components;

import java.util.List;

import com.example.model.Person;
import com.example.service.DatabaseService;
import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOContext;
import er.extensions.components.ERXComponent;

public class Main extends ERXComponent {
	private static final long serialVersionUID = 1L;

	public String nameInput;
	public String addressInput;
	public String phoneInput;
	public Person currentPerson;

	public Main(WOContext context) {
		super(context);
	}

	public List<Person> people() {
		return DatabaseService.getInstance().getAllPersons();
	}

	public WOActionResults addPerson() {
		if (nameInput != null && !nameInput.trim().isEmpty()) {
			DatabaseService.getInstance().createPerson(
				nameInput.trim(),
				addressInput != null ? addressInput.trim() : "",
				phoneInput != null ? phoneInput.trim() : ""
			);
			nameInput = "";
			addressInput = "";
			phoneInput = "";
		}
		return null;
	}

	public WOActionResults viewPerson() {
		NameDetail nameDetailPage = pageWithName(NameDetail.class);
		nameDetailPage.selectedPerson = currentPerson;
		nameDetailPage.mainPage = this;
		return nameDetailPage;
	}

	public WOActionResults deleteAllData() {
		DatabaseService.getInstance().deleteAllData();
		return null;
	}
}
